### ISSUE TITLE
The IfModule end tag will not be inserted ...

### ISSUE THREAD

**Issue by MikeschTheCat** [debops/ansible-apache#13]
If the `{% if debops__tpl_macros.get_openssl_version()|version_compare("0.9.8h", ">=") %}` Check Fails, the close Tag for "`</IfModule>`" will never be inserted.

The "`</IfModule>`" must be at the last Line of this File: 
`templates/etc/apache2/conf-available/local-debops_apache.conf.j2`

**Comment by ypid** [comment]
Thanks. Should be fixed in #15. I assume you did not run `debops.pki` on the host?

**Comment by MikeschTheCat** [comment]
Hello Robin,

yes, this is correct, we use our webservers behind an LoadBalancer with 
SSL-Offloading,
so we don't need pki on our webservers :)

Thanks & Regards
Mikesch

Am 13.02.17 um 19:24 schrieb Robin Schneider:

**Comment by ypid** [comment]
All right then. Should be fixed.

**Comment by MikeschTheCat** [comment]
Very thanks for the very fast fix :)


Am 13.02.17 um 19:35 schrieb Robin Schneider:
